### ISSUE TITLE
Links being omitted from sitemap sporadically

### ISSUE THREAD

**Issue by stickeedavid** [spatie/laravel-sitemap#252]
Hi, 

I'm unsure if the following is a bug or if I'm misunderstanding how the package works, but there seems to be URLs being omitted sporadically from the sitemap. 

I'm calling the SitemapGenerator in the most basic way possible: `SitemapGenerator::create(config('app.url'))->writeToFile(public_path('sitemap.xml'));`. If I implement the `shouldCrawl` method and simply list out all the URL's that are reached (returning true), it displays the paths I know to be missing - but they do not get included in the final sitemap.

I've had a look around, but I cannot find any issues similar to this. The site we use is the usual Laravel-style mix of Laravel and Vue components.

Cheers

**Comment by range-of-motion** [comment]
Same issue here, seems to be a history of "missing routes" for this package if you look at the closed issues.

**Comment by freekmurze** [comment]
> I'm calling the SitemapGenerator in the most basic way possible: SitemapGenerator::create(config('app.url'))->writeToFile(public_path('sitemap.xml'));. If I implement the shouldCrawl method and simply list out all the URL's that are reached (returning true), it displays the paths I know to be missing - but they do not get included in the final sitemap.

I do not see this problem in my own projects. Could you PR a test that demonstrates this problem?

**Comment by oad-dwarf** [comment]
I had a similar issue, and found that the links that did not get included in the sitemap were links with a full URL that were not part of the site hostname.

Example:

A test version of a site to be crawled: https://test.example.com, had full url links like https://example.com/about, but because example.com is not the site url, it did not get included. Solution might be to make the "missing" links on the site relative.

So it's a feature, not a bug 👍
