### ISSUE TITLE
is it possible to generate the sitemap to the laravel app with more than 200.000 pages?

### ISSUE THREAD

**Issue by refojunior** [spatie/laravel-sitemap#339]
Hi, I have a Laravel application that contains more than 200.000 pages, and the page will always increase weekly until monthly.
I have tried to generate the sitemap like this:
```
SitemapGenerator::create("https://example.com")
                        ->writeToFile(public_path('sitemap/sitemap.xml'));
```
The pages are basically from records on the database.
I tried to run it on the background process but always crashes the whole platform. Whenever I run this script, my application cannot be used at all.
Is anyone has a similar issue? Or how is the best way to approach this challenge?

**Comment by astalpaert** [comment]
I don't know if this is supported when I read the documentation on  [https://freek.dev/557-automatically-generate-a-sitemap-in-laravel] (**Limitations section**):

Our package is targeted at small to medium-sized apps. According to the specification a sitemap can hold up to 50 000 items (if have more links you'll need a sitemap index). There are also specific link types for video's, image's, etc... The package currently does not have support for sitemap indexes and these other types of links because it's not needed for any of our projects. I'd accept a PR that adds these things to our package.

Here are some alternatives that already support these features (but they don't include the crawler from our package)

refinery29/sitemap
RoumenDamianoff/laravel-sitemap
dwightwatson/sitemap
