### ISSUE TITLE
Laravel-sitemap installation

### ISSUE THREAD

**Issue by M-Art-Work** [spatie/laravel-sitemap#44]
Hello
I would use this package but there is a few stuff that i don't understand (i working on laravel since 3 month so quite a beginner).
I made **the first step** => composer require spatie/laravel-sitemap and **the second one** =>"Spatie\Sitemap\SitemapServiceProvider::class," then **the Third** =>SitemapGenerator::create('https://example.com')->writeToFile($path);

**My first question is** : could i put the "SitemapGenerator::create('https://example.com')->writeToFile($path);" every where i want (i put it in my Controllers\Controller.php 

**Second question** : Do i have to run a php artisan command to execute the process ?

**Third question** (if you have five minute more) : we put a provider, do i have to add an alias to the facade (SitemapGenerator) ? and then use it in the top of my controller ? (like use Illuminate\Foundation\Auth\Access\AuthorizesRequests; )

Thanks for All

**Comment by freekmurze** [comment]
Hi,

1. Yup, you can put the call anywhere you want
2. Not necessarily, if you put in in a controller that gets used in a web request, then the generating will do it's thing in that web request. But, because generating a sitemap can take some time (and you don't want a user of your site wait for that long) it's best practice to just create an artisan command and do the generating in there. You can schedule artisan commands so they run automatically at specified intervals. Refer to the Laravel docs to learn more. https://laravel.com/docs/5.3/artisan
3. You really don't need a Facade here. Just import the namespace at the top of your file:

```php
use namespace Spatie\Sitemap\ SitemapGenerator;
```

Have fun using the package.

**Comment by M-Art-Work** [comment]
Hello Thanks for your reply
I made à view + route for the sitemap link to a controller, in return i 've got this error message, do you know what is the good syntax pour the $path ?

file_put_contents(public/sitemap): failed to open stream: No such file or directory


<?php
namespace ineria\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Sitemap\SitemapGenerator;

class SitemapController extends Controller
{
  public function setSitemap(){
    SitemapGenerator::create('https://dev-maw.fr/ineria/public')->writeToFile('public/sitemap');
    return view('pages.ineria');
  }


}

**Comment by M-Art-Work** [comment]
Hello thanks you for your reply
I know you closed the issue and you seem’s to be busy but i have only one more question i don’t know how setup the path of the file where the sitemap will be written.

Just below my SitemapController who trigger the sitemap creation, but it return me an error that the path is not right, do you know how correct it ?
ErrorException
file_put_contents(public/sitemap): failed to open stream: No such file or directory

The controllers

namespace ineria\Http\Controllers;
use Illuminate\Http\Request;
use Spatie\Sitemap\SitemapGenerator;

class SitemapController extends Controller
{
  public function setSitemap(){

    SitemapGenerator::create('https://dev-maw.fr/ineria/public')->writeToFile('public/sitemap');

    return view('pages.sitemapegenerator');
  }

}


Best Regards

**Comment by M-Art-Work** [comment]
Sorry for the last mail i found the right path
have a good day
M
