### ISSUE TITLE
Crawling site with subdomains

### ISSUE THREAD

**Issue by gizburdt** [spatie/laravel-sitemap#90]
Hi,

For example, my site is `example.com`, and I have a subdomain `another.example.com`.
When I have this code: `SitemapGenerator::create($this->url)->writeToFile(...)`, the pages from `another.example.com` are not included in the sitemap. There are links to `another.example.com` on `example.com`.

Is there an option to include subdomains to the crawler maybe? 

Thanks! :)

**Comment by freekmurze** [comment]
The underlying crawler uses a `CrawlProfile` to determine which links should be crawled.

Currently a profile is hardwired this package: https://github.com/spatie/laravel-sitemap/blob/master/src/Crawler/Profile.php

In order to make the crawling more configurable we could add a new `crawl_profile` key in the config file which would contains the class name of a custom `CrawlProfile`.

I'd accept a fully tested, non-breaking PR that adds this to the package.

**Comment by gizburdt** [comment]
Could you maybe give me a small example on how to use the new feature to solve my problem? :)

**Comment by chrisrenga** [comment]
Hi @gizburdt see https://github.com/spatie/laravel-sitemap/pull/100.

I hope this helps.

**Comment by gizburdt** [comment]
Thanks :)

**Comment by alaster1985** [comment]
Hi
Is it possible to get sitemap content without saving to file?
